# Generated by Django 4.2.7 on 2024-10-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderhub', '0002_categoria_mesa_reserva_producto_pedido_pago_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], max_length=20),
        ),
    ]
