# Generated by Django 4.2.7 on 2024-12-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderhub', '0002_categoria_mesa_reserva_producto_pedido_pago_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='estado',
            field=models.CharField(blank=True, choices=[('NO_ENTREGADO', 'No_entregado'), ('ENTREGADO', 'Entregado')], max_length=20, null=True),
        ),
    ]
